# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/g2f_comp',
                'doc_host': 'https://danielkick.github.io',
                'git_url': 'https://github.com/danielkick/g2f_comp',
                'lib_path': 'g2f_comp'},
  'syms': {'g2f_comp.core': {'g2f_comp.core.foo': ('core.html#foo', 'g2f_comp/core.py')}}}
